---
- block:
  - name: Start db virtual machine
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      name: db
      state: poweredon
    delegate_to: localhost

  - name: Check for db running
    wait_for:
      port: 5432
      host: db.example.com
      delay: 3
      timeout: 60

  rescue:
    - name: Force off db virtual machine
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        name: db
        state: poweredoff
      delegate_to: localhost

    - pause:
        seconds: 10

    - name: Try again
      include_tasks: loop_db_vm.yml
