---
- block:
  - name: Start jboss1 virtual machine
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      name: jboss1
      state: poweredon
    delegate_to: localhost

  - name: Check for jboss1 running
    wait_for:
      port: 8443
      host: jboss1.example.com
      delay: 3
      timeout: 60

  rescue:
    - name: Force off jboss1 virtual machine
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        name: jboss1
        state: poweredoff
      delegate_to: localhost

    - pause:
        seconds: 10

    - name: Try again
      include_tasks: loop_jboss1_vm.yml
