---
- block:
  - name: Start lb virtual machine
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      name: lb
      state: poweredon
    delegate_to: localhost

  - name: Check for lb running
    wait_for:
      port: 443
      host: lb.example.com
      delay: 10

  rescue:
    - name: Force off lb virtual machine
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        name: lb
        state: poweredoff
      delegate_to: localhost

    - pause:
        seconds: 10

    - name: Try again
      include_tasks: loop_lb_vm.yml
