---
- block:
  - name: Start jboss0 virtual machine
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      name: jboss0
      state: poweredon
    delegate_to: localhost

  - name: Check for jboss0 running
    wait_for:
      port: 8443
      host: jboss0.example.com
      delay: 10

  rescue:
    - name: Force off jboss0 virtual machine
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        name: jboss0
        state: poweredoff
      delegate_to: localhost

    - pause:
        seconds: 10

    - name: Try again
      include_tasks: loop_jboss0_vm.yml
